name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore WindowsEasyEmoji.sln

      - name: Test
        run: dotnet test WindowsEasyEmoji.sln --configuration Release --no-restore

      - name: Build
        run: dotnet build WindowsEasyEmoji.sln --configuration Release --no-restore
